### PR TITLE
Telemetry_INT Modal Utilizes New Modal Component

### PR DESCRIPTION
**Pull request by HeriLFIU**
Closes #N/A

### Summary

A new modal component was added to the UI repository. This pull request makes it so that the telemetry_int UI now utilizes the new modal component.

### Local Tests

The new modal component was used on a single EVC with telemetry enabled and it functioned as should.
Successfully deleted 3 proxy ports.

#### Parent

Description - UI repo in which the new modal component was implemented

- https://github.com/kytos-ng/ui/pull/80

### Images

image

image

image

### CODE REVIEW

**Review by viniarck — COMMENTED** [review]
@HeriLFIU, regarding the `k-checkbox` that uses `force_del` on `list_proxy_ports.kytos`, maybe we could also removed it from the modal to leave the modal more pure with just its confirmation responsibility? If that simplifies for the modal, maybe the easiest route is to find another place to put the `k-checkbox` for the force option when deleting a proxy port. Think about it, if you can come up and identify any other place where we can move it, that's OK too.

**Comment by HeriLFIU** [comment]
@viniarck I took care of the last modal and updated the proxy port table. I also successfully deleted 3 proxy ports with the new modal component.

**Review by viniarck — COMMENTED** [review]
Nicely done @HeriLFIU, appreciated. Very neat the new column and the  deletion button turning red when force is set. This will get shipped once code freeze is over.

**Review by viniarck — APPROVED** [review]
Code freeze is over and https://github.com/kytos-ng/ui/pull/80 has landed. Let's ship it.

**Pull request merged**
